---
title: "bash"
toc: true
---

The `bash` subcommand is used to set up bash.

## Commands

```
  bash rc.d
  bash path
  bash login
```

### `bash rc.d`

To manage shell configuration more effectively, it is helpful to place individual scripts inside a dedicated directory (i.e. `~/.bashrc.d/`) rather than cluttering the main `~/.bashrc` file.
The `bash rc.d` command sets up this directory and configures your `~/.bashrc` to source all scripts inside it.

To set this up, run the following command:

```bash
setupmjr bash rc.d
```

::: {.callout-info collapse="true"}
## Details

The `bash rc.d` command configures the environment by doing the following:

1. It ensures the `~/.bashrc.d` directory exists.

2. It appends a loop to your `~/.bashrc` to automatically source any readable scripts inside `~/.bashrc.d/`:

    ```bash
    for i in $HOME/.bashrc.d/*; do [ -r "$i" ] && source "$i"; done
    ```
:::


### `bash path`

Often, custom executables and scripts are stored in standard local directories like `~/bin` or `~/.local/bin`. To execute these seamlessly, these directories need to be appended to the system `PATH`.
The `bash path` command provides a shell-agnostic way to add these directories to your path by placing a script (`path-executables.sh`) inside `~/.bashrc.d/`.

To set this up, run the following command:

```bash
setupmjr bash path
```

::: {.callout-info collapse="true"}
## Details

The `bash path` command ensures `~/bin` and `~/.local/bin` are accessible by doing the following:

1. It calls `bash rc.d` to ensure the `~/.bashrc.d/` directory is properly set up and sourced by `~/.bashrc`.

2. It copies an embedded script, `path-executables.sh`, to `~/.bashrc.d/path-executables.sh`. This script safely appends `~/bin` and `~/.local/bin` to the `PATH` environment variable if they are not already included.
:::
