name: Publish Quarto Site

on:
  push:
    branches: [main]

permissions:
  contents: write
  pages: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Publish Quarto Site
        uses: MiguelRodo/actions/publish-quarto-site@bf850afe48d42ac221079cfede39021d0574c15a # v3.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
